version: '3.8'

services:
  # Go 應用程式
  go-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/app.db
    volumes:
      - app_data:/app/data
      - ./logs:/app/logs  # 映射日誌目錄到本地
    restart: unless-stopped
    container_name: go-simple-app

volumes:
  app_data: