version: '3.8'

services:
  # Go 應用程式
  go-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/app.db
      - MONGODB_URI=mongodb+srv://genhow2000_db_user:PKwCLU4qXzrpAjSY@cluster0.atzcxpw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_DATABASE=chatbot
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - AI_PRIMARY_PROVIDER=groq
      - AI_FALLBACK_PROVIDER=gemini
    volumes:
      - app_data:/app/data
      - ./logs:/app/logs  # 映射日誌目錄到本地
    restart: unless-stopped
    container_name: go-simple-app
    networks:
      - default

volumes:
  app_data: