version: '3.8'

services:
  # Go 應用程式
  go-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_PATH=/app/data/app.db
      - MONGODB_URI=mongodb+srv://genhow2000_db_user:PKwCLU4qXzrpAjSY@cluster0.atzcxpw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGODB_DATABASE=chatbot
      - JWT_SECRET=${JWT_SECRET:-go-web-app-super-secret-jwt-key-2024}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - AI_PRIMARY_PROVIDER=groq
      - AI_FALLBACK_PROVIDER=gemini
      - LINE_CLIENT_ID=${LINE_CLIENT_ID:-2008159551}
      - LINE_CLIENT_SECRET=${LINE_CLIENT_SECRET:-2cca495d6b53e8b2a2d684ee87113f01}
      - LINE_REDIRECT_URL=${LINE_REDIRECT_URL:-http://localhost:8080/auth/line/callback}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
    volumes:
      - app_data:/app/data
      - ./logs:/app/logs  # 映射日誌目錄到本地
    restart: unless-stopped
    container_name: go-simple-app
    networks:
      - default

volumes:
  app_data: