name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: fleet-day-383710
  SERVICE_NAME: go-app
  REGION: asia-east1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          echo "Building Docker image..."
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .
          echo "Pushing Docker image..."
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
          echo "Docker image pushed successfully!"

      - name: Deploy to Cloud Run
        run: |
          # 使用固定的服務 URL (舊格式)
          SERVICE_URL="https://go-app-313144253156.asia-east1.run.app"

          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 8080 \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 10 \
            --min-instances 0 \
            --set-env-vars "DB_PATH=/tmp/app.db" \
            --set-env-vars "STATIC_PATH=/root/static" \
            --set-env-vars "MONGODB_URI=${{ secrets.MONGODB_URI }}" \
            --set-env-vars "MONGODB_DATABASE=chatbot" \
            --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
            --set-env-vars "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" \
            --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
            --set-env-vars "AI_PRIMARY_PROVIDER=groq" \
            --set-env-vars "AI_FALLBACK_PROVIDER=gemini" \
            --set-env-vars "LINE_CLIENT_ID=${{ secrets.LINE_CLIENT_ID }}" \
            --set-env-vars "LINE_CLIENT_SECRET=${{ secrets.LINE_CLIENT_SECRET }}" \
            --set-env-vars "LINE_REDIRECT_URL=$SERVICE_URL/auth/line/callback" \
            --set-env-vars "BASE_URL=$SERVICE_URL" \
            --set-env-vars "FRONTEND_URL=$SERVICE_URL"

      - name: Show Output
        run: |
          echo "Service deployed at:"
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --region=$REGION --format="value(status.url)")
          echo $SERVICE_URL
          echo "::notice::Deployment successful! Service URL: $SERVICE_URL"
